version: 2.1

parameters:
  specgen-version:
    type: string
    default: 1.10.32

jobs:
  service-go:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/service-tests
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: ./zips
          destination: zips
      - store_artifacts:
          path: ./dist
          destination: service-tests
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - run:
          name: Release
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              ./release.sh << pipeline.parameters.specgen-version >> ${GITHUB_TOKEN}
            else
              echo "Will not release - not running on main branch"
            fi

workflows:
  service-tests:
    jobs:
      - service-go:
          context: specgen